[2021-10-21 12:15:35,680] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bigquery.upload manual__2021-10-21T10:15:30.803277+00:00 [queued]>
[2021-10-21 12:15:35,683] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: bigquery.upload manual__2021-10-21T10:15:30.803277+00:00 [queued]>
[2021-10-21 12:15:35,683] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 12:15:35,684] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-21 12:15:35,684] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 12:15:35,688] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-10-21 10:15:30.803277+00:00
[2021-10-21 12:15:35,693] {standard_task_runner.py:52} INFO - Started process 23419 to run task
[2021-10-21 12:15:35,697] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery', 'upload', 'manual__2021-10-21T10:15:30.803277+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/csv_2_bigquery.py', '--cfg-path', '/var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T/tmpw_58mwys', '--error-file', '/var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T/tmpdwt4d5q8']
[2021-10-21 12:15:35,699] {standard_task_runner.py:77} INFO - Job 13: Subtask upload
[2021-10-21 12:15:35,718] {logging_mixin.py:109} INFO - Running <TaskInstance: bigquery.upload manual__2021-10-21T10:15:30.803277+00:00 [running]> on host 28.0.168.192.in-addr.arpa
[2021-10-21 12:15:35,733] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=vinzenz@9fwr.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigquery
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-10-21T10:15:30.803277+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-21T10:15:30.803277+00:00
[2021-10-21 12:15:35,734] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/fc/65rvsktx5tv__l89pnq2m4pw0000gn/T
[2021-10-21 12:15:35,734] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /Users/cesareborgia/Desktop/9fwr/airflow_use_case/get_data.py; echo success']
[2021-10-21 12:15:35,743] {subprocess.py:85} INFO - Output:
[2021-10-21 12:15:35,843] {subprocess.py:89} INFO - Traceback (most recent call last):
[2021-10-21 12:15:35,844] {subprocess.py:89} INFO -   File "/Users/cesareborgia/Desktop/9fwr/airflow_use_case/get_data.py", line 2, in <module>
[2021-10-21 12:15:35,844] {subprocess.py:89} INFO -     import pandas as pd
[2021-10-21 12:15:35,844] {subprocess.py:89} INFO - ModuleNotFoundError: No module named 'pandas'
[2021-10-21 12:15:35,851] {subprocess.py:89} INFO - success
[2021-10-21 12:15:35,851] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-21 12:15:35,860] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=bigquery, task_id=upload, execution_date=20211021T101530, start_date=20211021T101535, end_date=20211021T101535
[2021-10-21 12:15:35,891] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-21 12:15:35,899] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
